services:
    app.provider.balance.history:
        class: RusLan\ResolveTest\Balance\AppBundle\Provider\Balance\HistoryProvider
        calls:
            - [ setRepository, [ '@app.repository.balance.history' ] ]
