version: "3.6"

services:
  nginx:
    image: nginx:${NGINX_VERSION}
    hostname: ${COMPOSE_PROJECT_NAME}_nginx
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    restart: unless-stopped
    depends_on:
      - site
    volumes:
      - ../../../modules/balance:/app:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/include/:/etc/nginx/include
    ports:
      - 8080:80
    networks:
      local_network:
        ipv4_address: 192.168.220.2
      default:

  site:
    hostname: ${COMPOSE_PROJECT_NAME}_site
    container_name: ${COMPOSE_PROJECT_NAME}_site
    build:
      context: ../../..
      dockerfile: resources/deployments/local/site/php/Dockerfile
      args:
        HOME: "$HOME"
        USER: "$USER"
        UID: "$UID"
        GID: "$GID"
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    restart: unless-stopped
    volumes:
      - ../../../modules/site:/app:cached
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - ${HOME}/.composer:${HOME}/.composer
    expose:
      - "9000"
    networks:
      local_network:
        ipv4_address: 192.168.220.12
      default:

  balance:
    hostname: ${COMPOSE_PROJECT_NAME}_balance
    container_name: ${COMPOSE_PROJECT_NAME}_balance
    build:
      context: ../../..
      dockerfile: resources/deployments/local/balance/php/Dockerfile
      args:
        HOME: "$HOME"
        USER: "$USER"
        UID: "$UID"
        GID: "$GID"
        COMPOSER_VERSION: ${COMPOSER_VERSION}
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ../../../modules/balance:/app:cached
      - ${HOME}/.ssh:${HOME}/.ssh:ro
      - ${HOME}/.composer:${HOME}/.composer
    expose:
      - "9000"
    networks:
      local_network:
        ipv4_address: 192.168.220.11
      default:

  db:
    hostname: ${COMPOSE_PROJECT_NAME}_db
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      local_network:
        ipv4_address: 192.168.220.10
      default:

volumes:
  db_data:

networks:
  local_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/24
