json-rpc-endpoint:
    resource: '@JsonRpcHttpServerBundle/Resources/config/routing/endpoint.xml'
json-rpc-endpoint-doc:
    resource: '@JsonRpcHttpServerDocBundle/Resources/config/routing/endpoint.xml'
